// <auto-generated />
using System;
using MacroCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MacroCalculator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514152508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MacroCalculator.Models.DailyLog", b =>
                {
                    b.Property<int>("DailyLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DailyLogId"));

                    b.Property<int>("CaloriesRemaining")
                        .HasColumnType("int");

                    b.Property<decimal>("CarbsRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FatRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FiberRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ProteinRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalCaloriesConsumed")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCarbsConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalFatConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalFiberConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalProteinConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DailyLogId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("MacroCalculator.Models.FoodEntry", b =>
                {
                    b.Property<int>("FoodEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FoodEntryId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CustomMealName")
                        .HasColumnType("longtext");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Fiber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SavedMealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEaten")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FoodEntryId");

                    b.HasIndex("DailyLogId");

                    b.HasIndex("SavedMealId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("MacroCalculator.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("int");

                    b.Property<decimal>("CarbsPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DefaultServingSize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MacroCalculator.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealIngredientId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityInGrams")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SavedMealId")
                        .HasColumnType("int");

                    b.HasKey("MealIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("SavedMealId");

                    b.ToTable("MealIngredients");
                });

            modelBuilder.Entity("MacroCalculator.Models.SavedMeal", b =>
                {
                    b.Property<int>("SavedMealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SavedMealId"));

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Fiber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MealCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ServingSize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SavedMealId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedMeals");
                });

            modelBuilder.Entity("MacroCalculator.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("GoalWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TargetCarbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetFat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetFiber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetProtein")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MacroCalculator.Models.WeightProgress", b =>
                {
                    b.Property<int>("WeightProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WeightProgressId"));

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("WeightProgressId");

                    b.HasIndex("UserId");

                    b.ToTable("WeightProgressEntries");
                });

            modelBuilder.Entity("MacroCalculator.Models.DailyLog", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.FoodEntry", b =>
                {
                    b.HasOne("MacroCalculator.Models.DailyLog", "DailyLog")
                        .WithMany("FoodEntries")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MacroCalculator.Models.SavedMeal", "SavedMeal")
                        .WithMany("FoodEntries")
                        .HasForeignKey("SavedMealId");

                    b.Navigation("DailyLog");

                    b.Navigation("SavedMeal");
                });

            modelBuilder.Entity("MacroCalculator.Models.MealIngredient", b =>
                {
                    b.HasOne("MacroCalculator.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MacroCalculator.Models.SavedMeal", "SavedMeal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("SavedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("SavedMeal");
                });

            modelBuilder.Entity("MacroCalculator.Models.SavedMeal", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("SavedMeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.WeightProgress", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("WeightProgressEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.DailyLog", b =>
                {
                    b.Navigation("FoodEntries");
                });

            modelBuilder.Entity("MacroCalculator.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("MacroCalculator.Models.SavedMeal", b =>
                {
                    b.Navigation("FoodEntries");

                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("MacroCalculator.Models.User", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("SavedMeals");

                    b.Navigation("WeightProgressEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
