// <auto-generated />
using System;
using MacroCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MacroCalculator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MacroCalculator.Models.DailyLog", b =>
                {
                    b.Property<int>("DailyLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DailyLogId"));

                    b.Property<int>("CaloriesRemaining")
                        .HasColumnType("int");

                    b.Property<decimal>("CarbsRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FatRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FiberRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ProteinRemaining")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalCaloriesConsumed")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCarbsConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalFatConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalFiberConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalProteinConsumed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DailyLogId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLogs");

                    b.HasData(
                        new
                        {
                            DailyLogId = 1,
                            CaloriesRemaining = 550,
                            CarbsRemaining = 60m,
                            FatRemaining = 23m,
                            FiberRemaining = 11m,
                            LogDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProteinRemaining = 45m,
                            TotalCaloriesConsumed = 1100,
                            TotalCarbsConsumed = 120m,
                            TotalFatConsumed = 32m,
                            TotalFiberConsumed = 14m,
                            TotalProteinConsumed = 75m,
                            UserId = 1
                        },
                        new
                        {
                            DailyLogId = 2,
                            CaloriesRemaining = 170,
                            CarbsRemaining = 20m,
                            FatRemaining = 9m,
                            FiberRemaining = 4m,
                            LogDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProteinRemaining = 25m,
                            TotalCaloriesConsumed = 1480,
                            TotalCarbsConsumed = 160m,
                            TotalFatConsumed = 46m,
                            TotalFiberConsumed = 21m,
                            TotalProteinConsumed = 95m,
                            UserId = 1
                        },
                        new
                        {
                            DailyLogId = 3,
                            CaloriesRemaining = 40,
                            CarbsRemaining = 6m,
                            FatRemaining = 5m,
                            FiberRemaining = 2m,
                            LogDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProteinRemaining = 18m,
                            TotalCaloriesConsumed = 1610,
                            TotalCarbsConsumed = 174m,
                            TotalFatConsumed = 50m,
                            TotalFiberConsumed = 23m,
                            TotalProteinConsumed = 102m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.FoodEntry", b =>
                {
                    b.Property<int>("FoodEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FoodEntryId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CustomMealName")
                        .HasColumnType("longtext");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Fiber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MealType")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SavedMealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEaten")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FoodEntryId");

                    b.HasIndex("DailyLogId");

                    b.HasIndex("SavedMealId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodEntries");

                    b.HasData(
                        new
                        {
                            FoodEntryId = 1,
                            Calories = 520,
                            Carbs = 74m,
                            DailyLogId = 1,
                            Fat = 12m,
                            Fiber = 8m,
                            Notes = "Lunch meal",
                            Protein = 18m,
                            Quantity = 1m,
                            SavedMealId = 1,
                            TimeEaten = new DateTime(2026, 5, 14, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            FoodEntryId = 2,
                            Calories = 340,
                            Carbs = 28m,
                            DailyLogId = 1,
                            Fat = 9m,
                            Fiber = 5m,
                            Notes = "Breakfast smoothie",
                            Protein = 32m,
                            Quantity = 1m,
                            SavedMealId = 2,
                            TimeEaten = new DateTime(2026, 5, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            FoodEntryId = 3,
                            Calories = 410,
                            Carbs = 40m,
                            CustomMealName = "Chicken Wrap",
                            DailyLogId = 2,
                            Fat = 14m,
                            Fiber = 4m,
                            Notes = "Yesterday lunch",
                            Protein = 35m,
                            Quantity = 1m,
                            TimeEaten = new DateTime(2026, 5, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            FoodEntryId = 4,
                            Calories = 680,
                            Carbs = 82m,
                            CustomMealName = "Eba and Egusi",
                            DailyLogId = 3,
                            Fat = 24m,
                            Fiber = 10m,
                            Notes = "Dinner",
                            Protein = 28m,
                            Quantity = 1m,
                            TimeEaten = new DateTime(2026, 5, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("int");

                    b.Property<decimal>("CarbsPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DefaultServingSize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UnitName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId");

                    b.HasIndex("UserId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CaloriesPer100g = 130,
                            CarbsPer100g = 28m,
                            Category = "Grain",
                            DefaultServingSize = 100m,
                            FatPer100g = 0.3m,
                            FiberPer100g = 0.4m,
                            IngredientName = "White Rice",
                            MeasurementType = "Grams",
                            ProteinPer100g = 2.5m,
                            UserId = 1
                        },
                        new
                        {
                            IngredientId = 2,
                            CaloriesPer100g = 116,
                            CarbsPer100g = 21m,
                            Category = "Protein",
                            DefaultServingSize = 100m,
                            FatPer100g = 0.5m,
                            FiberPer100g = 6m,
                            IngredientName = "Black Eyed Beans",
                            MeasurementType = "Grams",
                            ProteinPer100g = 8m,
                            UserId = 1
                        },
                        new
                        {
                            IngredientId = 3,
                            CaloriesPer100g = 165,
                            CarbsPer100g = 0m,
                            Category = "Protein",
                            DefaultServingSize = 100m,
                            FatPer100g = 3.6m,
                            FiberPer100g = 0m,
                            IngredientName = "Chicken Breast",
                            MeasurementType = "Grams",
                            ProteinPer100g = 31m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MealIngredientId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityInGrams")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SavedMealId")
                        .HasColumnType("int");

                    b.HasKey("MealIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("SavedMealId");

                    b.ToTable("MealIngredients");

                    b.HasData(
                        new
                        {
                            MealIngredientId = 1,
                            IngredientId = 1,
                            QuantityInGrams = 200m,
                            SavedMealId = 1
                        },
                        new
                        {
                            MealIngredientId = 2,
                            IngredientId = 2,
                            QuantityInGrams = 150m,
                            SavedMealId = 1
                        },
                        new
                        {
                            MealIngredientId = 3,
                            IngredientId = 3,
                            QuantityInGrams = 180m,
                            SavedMealId = 3
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MacroCalculator.Models.SavedMeal", b =>
                {
                    b.Property<int>("SavedMealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SavedMealId"));

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Fiber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MealCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ServingSize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SavedMealId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedMeals");

                    b.HasData(
                        new
                        {
                            SavedMealId = 1,
                            Carbs = 74m,
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nigerian rice and black eyed beans",
                            Fat = 12m,
                            Fiber = 8m,
                            IsDeleted = false,
                            IsFavourite = true,
                            MealCategory = "Lunch",
                            MealName = "Rice and Beans",
                            Protein = 18m,
                            ServingSize = "1 Bowl",
                            TotalCalories = 520,
                            UserId = 1
                        },
                        new
                        {
                            SavedMealId = 2,
                            Carbs = 28m,
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Banana protein smoothie",
                            Fat = 9m,
                            Fiber = 5m,
                            IsDeleted = false,
                            IsFavourite = true,
                            MealCategory = "Breakfast",
                            MealName = "Protein Smoothie",
                            Protein = 32m,
                            ServingSize = "1 Glass",
                            TotalCalories = 340,
                            UserId = 1
                        },
                        new
                        {
                            SavedMealId = 3,
                            Carbs = 40m,
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chicken tortilla wrap",
                            Fat = 14m,
                            Fiber = 4m,
                            IsDeleted = false,
                            IsFavourite = false,
                            MealCategory = "Dinner",
                            MealName = "Chicken Wrap",
                            Protein = 35m,
                            ServingSize = "1 Wrap",
                            TotalCalories = 430,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("GoalWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TargetCarbs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetFat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetFiber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetProtein")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccountStatus = "Active",
                            ActivityLevel = "Moderate",
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentWeight = 78m,
                            DailyCalorieGoal = 1650,
                            DateOfBirth = new DateTime(2003, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            Gender = "Female",
                            GoalWeight = 65m,
                            Height = 167m,
                            LastLogin = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            PasswordHash = "password1",
                            PhoneNumber = "07111111111",
                            Role = "User",
                            TargetCarbs = 180m,
                            TargetFat = 55m,
                            TargetFiber = 25m,
                            TargetProtein = 120m,
                            Username = "alice"
                        },
                        new
                        {
                            UserId = 2,
                            AccountStatus = "Active",
                            ActivityLevel = "High",
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentWeight = 90m,
                            DailyCalorieGoal = 2400,
                            DateOfBirth = new DateTime(1999, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel@example.com",
                            FirstName = "Daniel",
                            Gender = "Male",
                            GoalWeight = 82m,
                            Height = 182m,
                            LastLogin = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            PasswordHash = "password2",
                            PhoneNumber = "07222222222",
                            Role = "User",
                            TargetCarbs = 250m,
                            TargetFat = 70m,
                            TargetFiber = 30m,
                            TargetProtein = 170m,
                            Username = "daniel"
                        },
                        new
                        {
                            UserId = 3,
                            AccountStatus = "Active",
                            ActivityLevel = "Low",
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentWeight = 60m,
                            DailyCalorieGoal = 1500,
                            DateOfBirth = new DateTime(2001, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maya@example.com",
                            FirstName = "Maya",
                            Gender = "Female",
                            GoalWeight = 58m,
                            Height = 160m,
                            LastLogin = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            PasswordHash = "password3",
                            PhoneNumber = "07333333333",
                            Role = "User",
                            TargetCarbs = 150m,
                            TargetFat = 45m,
                            TargetFiber = 22m,
                            TargetProtein = 100m,
                            Username = "maya"
                        },
                        new
                        {
                            UserId = 5,
                            AccountStatus = "Active",
                            ActivityLevel = "Moderate",
                            CreatedDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentWeight = 70m,
                            DailyCalorieGoal = 2000,
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@macrotrack.com",
                            FirstName = "System",
                            Gender = "Other",
                            GoalWeight = 70m,
                            Height = 170m,
                            LastName = "Administrator",
                            PasswordHash = "AQAAAAIAAYagAAAAEOc2E/C0AC69L165hupiYUmG6xX4N6fpVtt41NaIyU8TTGctlVjxob2bhv9260HjiQ==",
                            PhoneNumber = "07000000000",
                            Role = "Admin",
                            TargetCarbs = 220m,
                            TargetFat = 65m,
                            TargetFiber = 30m,
                            TargetProtein = 120m,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.WeightProgress", b =>
                {
                    b.Property<int>("WeightProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WeightProgressId"));

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("WeightProgressId");

                    b.HasIndex("UserId");

                    b.ToTable("WeightProgressEntries");

                    b.HasData(
                        new
                        {
                            WeightProgressId = 1,
                            DateRecorded = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Starting point",
                            UserId = 1,
                            Weight = 78m
                        },
                        new
                        {
                            WeightProgressId = 2,
                            DateRecorded = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Progress update",
                            UserId = 1,
                            Weight = 76.5m
                        },
                        new
                        {
                            WeightProgressId = 3,
                            DateRecorded = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Current weight",
                            UserId = 1,
                            Weight = 75.8m
                        });
                });

            modelBuilder.Entity("MacroCalculator.Models.DailyLog", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.FoodEntry", b =>
                {
                    b.HasOne("MacroCalculator.Models.DailyLog", "DailyLog")
                        .WithMany("FoodEntries")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MacroCalculator.Models.SavedMeal", "SavedMeal")
                        .WithMany("FoodEntries")
                        .HasForeignKey("SavedMealId");

                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("FoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");

                    b.Navigation("SavedMeal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.Ingredient", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("Ingredients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.MealIngredient", b =>
                {
                    b.HasOne("MacroCalculator.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MacroCalculator.Models.SavedMeal", "SavedMeal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("SavedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("SavedMeal");
                });

            modelBuilder.Entity("MacroCalculator.Models.Notification", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.SavedMeal", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("SavedMeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.WeightProgress", b =>
                {
                    b.HasOne("MacroCalculator.Models.User", "User")
                        .WithMany("WeightProgressEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MacroCalculator.Models.DailyLog", b =>
                {
                    b.Navigation("FoodEntries");
                });

            modelBuilder.Entity("MacroCalculator.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("MacroCalculator.Models.SavedMeal", b =>
                {
                    b.Navigation("FoodEntries");

                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("MacroCalculator.Models.User", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("FoodEntries");

                    b.Navigation("Ingredients");

                    b.Navigation("Notifications");

                    b.Navigation("SavedMeals");

                    b.Navigation("WeightProgressEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
